services:
  lexicon-service:
    build: lexicon-service/
    ports:
      - "8001:8001"
  mlm-service:
    build: mlm-service/
    ports:
      - "8002:8002"
  translation-service:
    build: translation-service/
    ports:
      - "8003:8003"
    