services:
  lexicon-service:
    build: services/lexicon-service/
    ports:
      - "8001:8001"
  mlm-service:
    build: services/mlm-service/
    ports:
      - "8002:8002"
  translation-service:
    build: services/translation-service/
    ports:
      - "8003:8003"
  text-partitioning-service:
    build: services/text-partitioning-service/
    ports:
      - "8004:8004"
    